#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

exit($app->handleCommand(new ArgvInput));
