// Contenido del manual de usuario, reutilizado por la seccion Ajustes de la app.
export interface ManualSection {
	id: string;
	title: string;
	text: string;
}

export const manualSections: ManualSection[] = [
	{
		id: "intro",
		title: "Introducción",
		text: [
			"===========================================================================",
			"  MI COMUNICADOR - MANUAL DE USUARIO",
			"  Guía general de la aplicación",
			"===========================================================================",
			"",
			"---------------------------------------------------------------------------",
			"  ¿QUÉ ES ESTA APP?",
			"---------------------------------------------------------------------------",
			"Mi Comunicador es una aplicación de Comunicación Aumentativa y Alternativa",
			"(CAA) pensada para niños y niñas con TEA o dificultades del lenguaje.",
			"",
			"En lugar de escribir, el niño toca pictogramas (dibujos) que se van",
			"uniendo para formar frases, y la app las dice en voz alta (TTS). También",
			"se puede grabar la voz de un familiar para que el niño la escuche.",
			"",
			"---------------------------------------------------------------------------",
			"  CONCEPTOS CLAVE QUE NECESITAS SABER",
			"---------------------------------------------------------------------------",
			"",
			"1) PICTOGRAMA",
			"   Dibujo o icono con una palabra debajo (ej. \"manzana\", \"quiero\", \"ir\").",
			"   Es la pieza básica para comunicarse. Cada tablero está lleno de",
			"   pictogramas y cada uno tiene una palabra.",
			"",
			"2) FRASE (o \"sentence\")",
			"   Es una fila de pictogramas que vas juntando en la barra inferior.",
			"   Cuando la frase está lista, se pulsa \"Hablar\" y la app la dice en voz",
			"   alta pegando las palabras de los pictogramas en orden.",
			"",
			"3) PERFIL",
			"   Es una \"identidad\" del niño dentro de la app. Cada perfil tiene su",
			"   propio nombre, sus tableros, sus frases favoritas, su modo de color y",
			"   su velocidad de voz. Puedes tener hasta 3 perfiles en un dispositivo.",
			"",
			"4) SECCIÓN (o \"tab\")",
			"   La app se divide en 4 secciones, navegables desde el menú inferior:",
			"     - Tableros  (📋) : los pictogramas organizados por categorías.",
			"     - Frases    (💬) : frases favoritas y grabaciones de voz.",
			"     - Rápido    (⚡) : accesos rápidos de uso frecuente.",
			"     - Ajustes   (⚙️) : perfiles, voz, modo visual, nube y modo logopeda.",
			"",
			"5) NUBE / CUENTA",
			"   Si inicias sesión con un correo, tus datos (tableros, frases,",
			"   grabaciones) se guardan en la nube y se sincronizan entre dispositivos.",
			"   Sin conexión a la nube, los datos solo quedan en ese dispositivo.",
			"",
			"---------------------------------------------------------------------------",
			"  CÓMO INICIAR SESIÓN (entrar a la app)",
			"---------------------------------------------------------------------------",
			"El inicio de sesión es OBLIGATORIO. Sin una cuenta no se entra a la app.",
			"",
			"1) La primera vez, elige \"Crear cuenta\" y pon un correo y una contraseña",
			"   (mínimo 8 caracteres, con letras y números).",
			"2) Las siguientes veces, elige \"Iniciar sesión\" con tu correo y contraseña.",
			"3) Al entrar, la app carga tus datos desde la nube (si ya tenías cuenta).",
			"",
			"Para salir: pulsa el botón de \"cerrar sesión\" que está junto al nombre del",
			"perfil, en la esquina superior derecha. La sesión también se cierra sola",
			"si estás 10 minutos sin usar la app.",
			"",
			"---------------------------------------------------------------------------",
			"  LA BARRA DE FRASE (parte más importante)",
			"---------------------------------------------------------------------------",
			"Debajo de todo, siempre visible, está la barra de frase. Ahí aparece el",
			"número de pictogramas que llevas unidos (\"N pictogramas\") y los chips de",
			"cada pictograma elegido.",
			"",
			"Botones de la barra de frase:",
			"  - [Borrar último] : quita el último pictograma que pusiste.",
			"  - [Borrar todo]   : vacía la frase completa (⚠ no pide confirmación).",
			"  - [Hablar]        : dice en voz alta TODA la frase armada.",
			"  - [Guardar]       : guarda la frase actual como favorita (sección Frases).",
			"  - [Mostrar/Ocultar menú] : pliega o despliega el menú inferior.",
			"",
			"Consejos:",
			"  - Toca cualquier chip de la frase para que la diga en voz alta.",
			"  - Toca la \"X\" de un chip para quitar SOLO ese pictograma.",
			"  - En tablet/pantalla grande los chips bajan a varias filas para que veas",
			"    más pictogramas a la vez; en móvil se deslizan a los lados.",
			"",
			"---------------------------------------------------------------------------",
			"  RESUMEN RÁPIDO DE USO",
			"---------------------------------------------------------------------------",
			"1. Abre la app e inicia sesión (o crea una cuenta).",
			"2. Ve a \"Tableros\" y toca pictogramas para armar una frase.",
			"3. Pulsa \"Hablar\" para que la diga.",
			"4. Pulsa \"Guardar\" para guardarla y poder repetirla después.",
			"5. Usa \"Frases\" para ver tus guardadas y grabar tu voz.",
			"6. Usa \"Ajustes\" para cambiar perfil, voz, color y modo logopeda.",
			"",
			"Cada sección tiene su propio manual independiente:",
			"  - 01-tableros.txt : cómo usar los tableros y buscar pictogramas.",
			"  - 02-frases.txt   : frases favoritas y grabaciones de voz.",
			"  - 03-rapido.txt   : accesos rápidos.",
			"  - 04-ajustes.txt  : perfiles, voz, nube y modo logopeda.",
			"===========================================================================",
			"",
		].join("\n"),
	},
	{
		id: "tableros",
		title: "Tableros",
		text: [
			"===========================================================================",
			"  MI COMUNICADOR - MANUAL DE USUARIO",
			"  Sección: TABLEROS (📋)",
			"===========================================================================",
			"",
			"---------------------------------------------------------------------------",
			"  ¿PARA QUÉ SIRVE ESTA SECCIÓN?",
			"---------------------------------------------------------------------------",
			"Los Tableros son el lugar principal para comunicarse. Contienen los",
			"pictogramas organizados por categorías (por ejemplo: alimentos, acciones,",
			"lugares, emociones...). Tocar un pictograma lo agrega a tu frase.",
			"",
			"---------------------------------------------------------------------------",
			"  LISTO DE TABLEROS (lado izquierdo / \"Navegación\")",
			"---------------------------------------------------------------------------",
			"Al entrar ves una lista de tableros disponibles. Toca el nombre de un",
			"tablero para abrirlo y ver sus pictogramas.",
			"",
			"- El tablero abierto se muestra resaltado.",
			"- Para volver al tablero anterior hay un botón \"Volver\" arriba (solo si",
			"  has entrado desde otro tablero).",
			"",
			"---------------------------------------------------------------------------",
			"  DENTRO DE UN TABLERO",
			"---------------------------------------------------------------------------",
			"Verás la cuadrícula de pictogramas. Cada pictograma es una tarjeta con un",
			"dibujo y su palabra.",
			"",
			"USUARIO NORMAL (niño o familia):",
			"  - Tocar un pictograma: lo agrega a la frase Y dice la palabra en voz",
			"    alta a la vez.",
			"  - Botón de altavoz (🔊) en una esquina del pictograma: solo dice esa",
			"    palabra SIN agregarla a la frase. Útil para enseñar vocabulario.",
			"  - Algunos pictogramas tienen una flecha (➤): son \"accesos\" que te llevan",
			"    a otro tablero relacionado al tocarlos.",
			"",
			"MODO LOGOPEDA (solo si estás con PIN, ver manual 04-ajustes):",
			"  - Se muestran botones extra: \"Renombrar tablero\", \"Agregar celda\",",
			"    \"Crear subtablero\", \"Agregar acceso\".",
			"  - Cada pictograma muestra botones \"Editar\" y \"Borrar\" para modificarlo.",
			"  - También permite añadir una foto real a una celda en lugar del icono.",
			"",
			"---------------------------------------------------------------------------",
			"  BÚSQUEDA DE PICTOGRAMAS (arriba, en el buscador)",
			"---------------------------------------------------------------------------",
			"En la parte superior hay una barra de búsqueda (\"Buscar pictograma\").",
			"",
			"  - Escribe una palabra y verás los pictogramas que la contienen.",
			"  - El título cambia a \"Resultados (N) para 'lo que buscaste'\".",
			"  - Toca un resultado para agregarlo a tu frase (como en el tablero).",
			"  - Para volver a la navegación normal, borra el texto del buscador.",
			"",
			"Esta búsqueda funciona desde cualquier sección, pero los resultados se",
			"muestran en la sección de Tableros.",
			"",
			"---------------------------------------------------------------------------",
			"  FLUJO RECOMENDADO PASO A PASO",
			"---------------------------------------------------------------------------",
			"1. Entra a la app e inicia sesión.",
			"2. Ve a la sección Tableros (📋).",
			"3. Toca un pictograma -> se agrega a la barra de frase abajo.",
			"4. Sigue tocando más pictogramas para armar tu frase completa.",
			"5. Cuando estés listo, pulsa \"Hablar\" (abajo) para que la diga.",
			"6. Si quieres guardarla para después, pulsa \"Guardar\".",
			"",
			"NOTA: los tableros, sus pictogramas y las celdas editadas por el logopeda",
			"se guardan por perfil y, si hay sesión activa, también en la nube.",
			"",
			"===========================================================================",
			"",
		].join("\n"),
	},
	{
		id: "frases",
		title: "Frases",
		text: [
			"===========================================================================",
			"  MI COMUNICADOR - MANUAL DE USUARIO",
			"  Sección: FRASES (💬)",
			"===========================================================================",
			"",
			"---------------------------------------------------------------------------",
			"  ¿PARA QUÉ SIRVE ESTA SECCIÓN?",
			"---------------------------------------------------------------------------",
			"En Frases guardas las frases que usas seguido para poder repetirlas con un",
			"solo toque. También aquí puedes GRABAR la voz de un familiar para que el",
			"niño escuche su propia voz en lugar de la voz sintetizada.",
			"",
			"---------------------------------------------------------------------------",
			"  PARTE 1: AYUDA PARA CREAR FRASE",
			"---------------------------------------------------------------------------",
			"Arriba de todo verás dos elementos para ayudarte a armar frases:",
			"",
			"A) PALABRAS DE CONEXIÓN (botones rápidos)",
			"   Son palabras como \"yo\", \"quiero\", \"no\", \"a\", \"con\", \"por favor\", etc.",
			"   Tocar una la agrega directo a tu frase. Son muy útiles para unir",
			"   pictogramas (ej. \"yo quiero ir a ...\").",
			"",
			"   - En pantalla grande los botones bajan a varias filas; en móvil se",
			"     deslizan a los lados.",
			"",
			"B) ESCRITURA MANUAL",
			"   Hay un cuadro de texto \"Escribe una palabra y agrégala\".",
			"   - Escribe una palabra o incluso una frase completa (hasta 120",
			"     caracteres) y pulsa \"Agregar\" (o la tecla Enter).",
			"   - Se añadirá a tu frase como un único elemento.",
			"   - Esto sirve, por ejemplo, para escribir palabras que no existen como",
			"     pictograma.",
			"",
			"---------------------------------------------------------------------------",
			"  PARTE 2: FRASES GUARDADAS (favoritas)",
			"---------------------------------------------------------------------------",
			"Cuando armas una frase en la barra inferior y pulsas \"Guardar\", aparece",
			"aquí como favorita.",
			"",
			"Cada frase favorita muestra un panel con:",
			"  - El texto de la frase (toda la frase junta, con las palabras en orden).",
			"  - Un botón \"X\" (rojo) para ELIMINAR la frase guardada (⚠ no pide",
			"    confirmación; se borra también su grabación si la tenía).",
			"",
			"Dentro del panel hay más botones:",
			"  - Tocar el texto de la frase: la dice en voz alta (TTS) y la vuelve a",
			"    poner en la barra de frase por si quieres modificarla.",
			"  - \"+ Agregar\": añade todos los pictogramas de esa favorita a la frase",
			"    actual (para combinarla con otras y hacer una más larga).",
			"  - \"Grabar voz familiar\": para grabar tu voz diciendo esa frase (ver",
			"    PARTE 3).",
			"  - \"Escuchar\": reproduce la grabación que guardaste.",
			"  - \"Descargar\": descarga la grabación como archivo de audio.",
			"",
			"---------------------------------------------------------------------------",
			"  PARTE 3: GRABAR LA VOZ DE UN FAMILIAR",
			"---------------------------------------------------------------------------",
			"El botón \"Grabar voz familiar\" permite que la frase se diga con TU voz en",
			"lugar de con la voz del dispositivo.",
			"",
			"1. Pulsa \"Grabar voz familiar\" (o \"Volver a grabar\" si ya hay una).",
			"2. La primera vez el navegador te pedirá permiso para usar el micrófono;",
			"   acepta el permiso.",
			"3. Habla la frase claramente.",
			"4. Pulsa \"Detener grabación\" cuando termines.",
			"5. Ya quedó guardada: pulsa \"Escuchar\" para comprobarla.",
			"",
			"NOTA IMPORTANTE (privacidad):",
			"  - La grabación se guarda SOLO en este dispositivo (local) y, si tienes",
			"    una sesión de nube iniciada, se envía a tu cuenta para que también",
			"    esté disponible en otros dispositivos tuyos. No se comparte con",
			"    nadie más.",
			"  - Si borras la frase favorita, su grabación también se elimina.",
			"  - Si grabas estando en \"modo logopeda\", la voz se marca como del",
			"    terapeuta.",
			"",
			"---------------------------------------------------------------------------",
			"  FLUJO RECOMENDADO PASO A PASO",
			"---------------------------------------------------------------------------",
			"1. Arma tu frase en Tableros (o con las palabras de conexión de aquí).",
			"2. Pulsa \"Guardar\" en la barra inferior -> aparece en Frases guardadas.",
			"3. Toca la frase para escucharla, o \"+ Agregar\" para volver a usarla.",
			"4. Si quieres tu voz: pulsa \"Grabar voz familiar\", habla y detén.",
			"5. Usa \"Escuchar\" y \"Descargar\" para reproducir o guardar el audio.",
			"",
			"===========================================================================",
			"",
		].join("\n"),
	},
	{
		id: "rapido",
		title: "Rápido",
		text: [
			"===========================================================================",
			"  MI COMUNICADOR - MANUAL DE USUARIO",
			"  Sección: RÁPIDO (⚡)",
			"===========================================================================",
			"",
			"---------------------------------------------------------------------------",
			"  ¿PARA QUÉ SIRVE ESTA SECCIÓN?",
			"---------------------------------------------------------------------------",
			"La sección Rápido reúne los pictogramas de USO MÁS FRECUENTE o de alta",
			"frecuencia, para que el niño pueda comunicar cosas cotidianas sin tener",
			"que buscar por todo el tablero.",
			"",
			"Es ideal para frases de la vida diaria que se repiten mucho: saludos,",
			"peticiones frecuentes, necesidades básicas, etc.",
			"",
			"---------------------------------------------------------------------------",
			"  \"ACCESO RÁPIDO\" (la cuadrícula principal)",
			"---------------------------------------------------------------------------",
			"Al entrar a Rápido verás el encabezado \"Acceso rápido\" y debajo una",
			"cuadrícula de pictogramas frecuentes.",
			"",
			"  - Tocar un pictograma: lo agrega a tu frase Y dice la palabra en voz",
			"    alta a la vez (igual que en Tableros).",
			"",
			"¿Para qué usarlo?",
			"  - Para armar frases cotidianas muy rápido, sin cambiar de tablero.",
			"  - Para mantener a la vista las palabras que el niño usa más seguido.",
			"",
			"---------------------------------------------------------------------------",
			"  BOTÓN \"MOSTRAR FRASES / OCULTAR FRASES\"",
			"---------------------------------------------------------------------------",
			"En la parte superior derecha hay un botón que dice \"Mostrar frases\" o",
			"\"Ocultar frases\" (en móvil se ve como \"Frases\" / \"Cerrar\").",
			"",
			"  - Sirve para desplegar o plegar el bloque de \"Frases rápidas\" que está",
			"    encima de la cuadrícula.",
			"  - Si lo plegas, ganas espacio en pantalla y ves la cuadrícula más",
			"    grande. Si lo despliegas, ves las frases rápidas adicionales.",
			"",
			"NOTA: el bloque de \"Frases rápidas\" (palabras de uso frecuente mostradas",
			"como botones grandes) está actualmente oculto en la barra inferior. En",
			"esta sección Rápido, el botón superior sigue permitiendo mostrarlo/ocultarlo",
			"según lo que necesites ver en pantalla.",
			"",
			"---------------------------------------------------------------------------",
			"  FLUJO RECOMENDADO PASO A PASO",
			"---------------------------------------------------------------------------",
			"1. Ve a la sección Rápido (⚡).",
			"2. Toca los pictogramas frecuentes que necesites para armar tu frase.",
			"3. Pulsa \"Hablar\" en la barra inferior para que la diga.",
			"4. Pulsa \"Guardar\" si quieres conservarla (la verás en Frases).",
			"",
			"COMBINA CON OTRAS SECCIONES:",
			"  - Si te falta una palabra que no está en Rápido, usa Tableros.",
			"  - Si la frase es fija y la usas mucho, guárdala para tenerla en Frases.",
			"",
			"===========================================================================",
			"",
		].join("\n"),
	},
	{
		id: "ajustes",
		title: "Ajustes",
		text: [
			"===========================================================================",
			"  MI COMUNICADOR - MANUAL DE USUARIO",
			"  Sección: AJUSTES (⚙️)",
			"===========================================================================",
			"",
			"Esta sección es la más completa. La usan la FAMILIA (perfiles, voz, color,",
			"nube) y también el LOGOPEDA (modo terapeuta y reportes).",
			"",
			"---------------------------------------------------------------------------",
			"  1) PERFILES",
			"---------------------------------------------------------------------------",
			"Los perfiles son las \"identidades\" dentro de la app (ej. \"Ana\", \"Luis\").",
			"",
			"- Selector de perfil: eliges cuál es el perfil activo. Cada perfil tiene",
			"  SUS propios tableros, frases, modo visual y velocidad de voz.",
			"- \"+ Agregar\": crea un nuevo perfil. Máximo 3 perfiles por dispositivo.",
			"- \"Eliminar\": borra el perfil activo (último solito no te deja borrar).",
			"- Cambiar de perfil carga sus datos automáticamente, sin mezclarlos.",
			"",
			"---------------------------------------------------------------------------",
			"  2) NUBE Y ACCESO (cuenta)",
			"---------------------------------------------------------------------------",
			"- Si la app no tiene API configurada, verás un aviso indicándolo.",
			"- Conectado como: muestra el correo con el que iniciaste sesión.",
			"- \"Cerrar sesión en la nube\": cierra la cuenta (volverá la pantalla de",
			"  login la próxima vez).",
			"- Si aún no has iniciado sesión desde Ajustes, puedes hacerlo aquí con tu",
			"  correo y contraseña (o \"Crear cuenta nueva\" si aún no tienes).",
			"- Estado de sincronización: abajo verás mensajes como \"Actualizando",
			"  cambios...\" o \"Datos sincronizados desde la nube\".",
			"- Si algo está por vencer, aparecerá un aviso naranja (⚠).",
			"",
			"¿Qué se guarda en la nube? Tableros, frases, config por perfil y",
			"grabaciones. Sirve para no perder los datos y usarlos en otro dispositivo.",
			"",
			"---------------------------------------------------------------------------",
			"  3) MODO VISUAL (Color de la app)",
			"---------------------------------------------------------------------------",
			"- \"Calma\": colores suaves (azules/grises), más relajante.",
			"- \"Color\": colores vivos y alegres (naranjas y brillantes).",
			"Este modo aplica a toda la app y se recuerda por perfil.",
			"",
			"---------------------------------------------------------------------------",
			"  4) VOZ Y VELOCIDAD",
			"---------------------------------------------------------------------------",
			"- VELOCIDAD: botones \"Lenta\", \"Media\" y \"Normal\" para ajustar lo rápido",
			"  que habla la voz sintetizada.",
			"- VOZ: selector donde eliges la voz que usa la app para hablar las frases.",
			"  Solo aparecen las voces disponibles en tu dispositivo (sistema y",
			"  navegador). Elige la que mejor entienda el niño.",
			"",
			"---------------------------------------------------------------------------",
			"  5) MODO TERAPEUTA / LOGOPEDA (🔒 con PIN)",
			"---------------------------------------------------------------------------",
			"Esta es la parte del profesional (logopeda/terapeuta). Permite editar",
			"tableros y generar reportes.",
			"",
			"CÓMO ENTRAR:",
			"  - Pulsa \"Entrar con PIN\".",
			"  - La primera vez te pedirá CREAR un PIN (mínimo 4 caracteres) y",
			"    confirmarlo.",
			"  - Después, cada vez que quieras entrar pedirá ese PIN.",
			"  - Si olvidaste el PIN: pulsa \"Olvidaste el PIN? Restablecer\" (requiere",
			"    confirmación) para crear uno nuevo.",
			"  - Para salir: pulsa \"Salir del modo terapeuta\".",
			"",
			"UNA VEZ DENTRO, podrás:",
			"  - Editar tu nombre (logopeda), número de colegiado y observaciones.",
			"  - Cambiar tu PIN.",
			"  - En Tableros: renombrar tableros, agregar/editar/borrar celdas, crear",
			"    subtableros, agregar accesos y asignar fotos reales.",
			"  - En Frases: la voz que grabes se marca como del terapeuta.",
			"  - En la pestaña LOGOPEDA 🔒 (nueva, solo visible con el modo activo): ver",
			"    el REGISTRO DE SESIÓN y generar reportes (ver parte 6).",
			"",
			"---------------------------------------------------------------------------",
			"  6) REGISTRO DE SESIÓN Y REPORTES (solo modo terapeuta)",
			"---------------------------------------------------------------------------",
			"Con el modo terapeuta activo aparece en el menú inferior una pestaña nueva",
			"\"LOGOPEDA 🔒\" (a la derecha de Ajustes). Al pulsarla se abre la vista del",
			"registro de sesión, amplia y cómoda. La app registra automáticamente cada",
			"vez que se pulsa \"Hablar\" (cada frase comunicada).",
			"",
			"- FILTRO POR RANGO: botones \"Hoy\", \"7 días\", \"30 días\", \"Todo\" y",
			"  \"Personalizado\" (eligiendo dos fechas).",
			"- MÉTRICAS: se muestran 3 cifras:",
			"    * Frases visibles  : cuántas frases hay en el período elegido.",
			"    * Frases únicas    : cuántas frases DIFERENTES se dijeron.",
			"    * Vocabulario activo: cuántas palabras distintas en total.",
			"- RESUMEN: un texto te dice quién, en qué período, cuántas frases comunicó",
			"  y cuáles fueron las 3 más usadas.",
			"- \"Descargar PDF\": genera un reporte de sesión en PDF (con nombre,",
			"  colegiado y observaciones del logopeda si los llenaste).",
			"- \"Borrar período\" / \"Borrar todo\": elimina el registro del rango",
			"  seleccionado (⚠ pide confirmación y NO se puede deshacer).",
			"",
			"USO TÍPICO DEL LOGOPEDA:",
			"1. Entrar con PIN en Ajustes (se abre automáticamente la pestaña LOGOPEDA).",
			"2. En Tableros, personalizar tableros y pictogramas del niño.",
			"3. En la pestaña LOGOPEDA, ver las cifras del período (Hoy / 7 días / 30).",
			"4. Descargar el PDF del reporte para el seguimiento clínico.",
			"",
			"===========================================================================",
			"  CONSEJO FINAL DE SEGURIDAD",
			"===========================================================================",
			"- No compartas tu PIN con nadie; protege los ajustes del niño.",
			"- La sesión de nube se cierra sola tras 10 minutos sin usar la app.",
			"- Los datos se guardan por perfil y se sincronizan con tu cuenta: cierra",
			"  sesión al prestar el dispositivo si quieres mantener la privacidad.",
			"",
			"===========================================================================",
			"",
		].join("\n"),
	},
]
